# backend/template.yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: hello_world.handler
      Runtime: python3.8
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get
