# backend/template.yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  SamRoyIoApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - backend.app.samroy.io
        Origins:
          - Id: SamRoyIoApiOrigin
            DomainName:
              Fn::Join:
                - ""
                - - Ref: SamRoyIoApi
                  - ".execute-api."
                  - Ref: AWS::Region
                  - ".amazonaws.com"
            OriginPath: "/prod" # Adjust the stage name if necessary
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: "https-only"
              OriginSSLProtocols:
                - TLSv1.2
        DefaultCacheBehavior:
          TargetOriginId: SamRoyIoApiOrigin
          ViewerProtocolPolicy: "redirect-to-https"
          CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          ForwardedValues:
            QueryString: true
            Headers:
              - Authorization
          LambdaFunctionAssociations: []
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:917324635987:certificate/4bd6ddff-2df5-4794-ab6b-ef36e15a47a0
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2018

  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get_health_check/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HealthCheck:
          Type: Api
          Properties:
            RestApiId: !Ref SamRoyIoApi
            Path: /health_check
            Method: get

  PostVisitorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/post_visitor/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VisitorCountTable
      Events:
        PostVisitorApi:
          Type: Api
          Properties:
            RestApiId: !Ref SamRoyIoApi
            Path: /post_visitor
            Method: post

  GetVisitorCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get_visitor_count/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VisitorCountTable
      Events:
        PostVisitorApi:
          Type: Api
          Properties:
            RestApiId: !Ref SamRoyIoApi
            Path: /get_visitor_count
            Method: get

  VisitorCountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VisitorCount
      AttributeDefinitions:
        - AttributeName: VisitorId
          AttributeType: S
      KeySchema:
        - AttributeName: VisitorId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
