name: Deploy Backend

on:
  push:
    branches:
      - main # Set this to your default branch
    paths:
      - "/backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy backend
        run: |
          cd backend
          pip install -r requirements.txt
          sam build
          sam deploy --guided
