name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend.yml"

jobs:
  # setup-s3-bucket:
  #   runs-on: ubuntu-latest
  #   env:
  #     AWS_REGION: "us-west-1" # Set your AWS region here
  #     AWS_S3_BUCKET: backend.app.samroy.io # Set your S3 bucket name here
  #   steps:
  #     - name: Create S3 bucket if it does not exist
  #       run: |
  #         if ! aws s3 ls "s3://$AWS_S3_BUCKET" 2>&1 | grep -q 'NoSuchBucket'; then
  #           echo "Bucket already exists"
  #         else
  #           aws s3 mb "s3://$AWS_S3_BUCKET" --region $AWS_REGION
  #           echo "Bucket created"
  #         fi
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli aws-sam-cli

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Build SAM application
        run: |
          sam build --template template.yaml

      - name: Deploy SAM application
        run: |
          sam deploy --resolve-s3 --stack-name samroyio-backend-stack --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset --template-file .aws-sam/build/template.yaml
